name: Download Rust offline package
on: workflow_dispatch

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs -o rustup-init.sh
          chmod +x rustup-init.sh
          ./rustup-init.sh -y --no-modify-path
          source ~/.cargo/env
          # بسته‌بندی کل دایرکتوری .cargo
          tar -czf rust-offline.tar.gz ~/.cargo
      - uses: actions/upload-artifact@v4
        with:
          name: rust-offline
          path: rust-offline.tar.gz
